/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type ZoneCandidate struct {
	// Name of zone
	ZoneName string `json:"zone_name,omitempty"`
	// Status of zone
	Status string `json:"status,omitempty"`
}
