/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type ProxyConfiguration struct {
	// An identifier of the source system - used for making compatibility changes
	Personality string `json:"personality,omitempty"`
	// The configuration
	Content string `json:"content"`
	// Message describing the configuration change
	Message string `json:"message,omitempty"`
	// JSON blob containing features for this proxy
	Features string `json:"features,omitempty"`
	// Content of the generated code
	GeneratedContent string `json:"generatedContent,omitempty"`
}
