/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Body3 struct {
	// Zone Name
	ZoneName string `json:"zoneName"`
	// Hostname
	Hostname string `json:"hostname,omitempty"`
}
