/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type ZoneRecord struct {
	Name string `json:"name,omitempty"`
	Ttl int32 `json:"ttl,omitempty"`
	RecordType string `json:"record_type,omitempty"`
	RecordData []ErrorUnknown `json:"record_data,omitempty"`
}
