/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type EnvironmentSummary struct {
	Id int32 `json:"id,omitempty"`
	Href string `json:"href,omitempty"`
	EnvironmentName string `json:"environment_name,omitempty"`
	Domains []DomainSummary `json:"domains,omitempty"`
	IsHosted bool `json:"is_hosted,omitempty"`
	DnsBypassAddress string `json:"dns_bypass_address,omitempty"`
}
