/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Totp struct {
	Base32text string `json:"base32text,omitempty"`
	Svg string `json:"svg,omitempty"`
	Url string `json:"url,omitempty"`
	PngDataUri string `json:"png_data_uri,omitempty"`
}
