/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Body1 struct {
	// Record Name
	RecordName string `json:"recordName"`
	// Record Type
	RecordType string `json:"recordType"`
	// Original Record Type
	OriginalRecordType string `json:"originalRecordType,omitempty"`
	// Time to live (seconds)
	Ttl int32 `json:"ttl"`
	// Record Data
	RecordData []ErrorUnknown `json:"recordData"`
}
