/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type DomainSummary struct {
	Name string `json:"name,omitempty"`
	ZoneName string `json:"zoneName,omitempty"`
	Cname string `json:"cname,omitempty"`
	Mode string `json:"mode,omitempty"`
}
