/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type HttpsConfiguration struct {
	Type_ string `json:"type,omitempty"`
	Configured bool `json:"configured,omitempty"`
	CommonName string `json:"common_name,omitempty"`
	AlternateNames []string `json:"alternate_names,omitempty"`
	Issuer string `json:"issuer,omitempty"`
	Expires string `json:"expires,omitempty"`
	Certificates []string `json:"certificates,omitempty"`
	HpkpFingerprint string `json:"hpkp_fingerprint,omitempty"`
	HostnameValid bool `json:"hostname_valid,omitempty"`
}
