/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type OutagePage struct {
	Name string `json:"name,omitempty"`
	Engaged bool `json:"engaged,omitempty"`
}
