/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type ZoneSummary struct {
	ZoneName string `json:"zone_name,omitempty"`
	NameServers []string `json:"name_servers,omitempty"`
}
