/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Body2 struct {
	PublicCertificates string `json:"public_certificates,omitempty"`
	PrivateKey string `json:"private_key,omitempty"`
}
