/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Application struct {
	Id int32 `json:"id,omitempty"`
	Href string `json:"href,omitempty"`
	ApplicationName string `json:"application_name,omitempty"`
	PathPrefix string `json:"path_prefix,omitempty"`
	PathPrefixes []string `json:"path_prefixes,omitempty"`
}
