/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type HttpsSetConfiguration struct {
	Type_ string `json:"type,omitempty"`
	VerifyOnly bool `json:"verify_only,omitempty"`
	PublicCertificates string `json:"public_certificates,omitempty"`
	PrivateKey string `json:"private_key,omitempty"`
}
