/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type EgressOrigin struct {
	Address *HostAddressDnsOrIp `json:"address"`
	HttpPort int32 `json:"http_port,omitempty"`
	HttpsPort int32 `json:"https_port,omitempty"`
	HostHeader *HostAddressDns `json:"host_header,omitempty"`
	DisableKeepalive bool `json:"disable_keepalive,omitempty"`
	KeepaliveSeconds int32 `json:"keepalive_seconds,omitempty"`
	TlsName *HostAddressDns `json:"tls_name,omitempty"`
}
