/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type BillingHistory struct {
	// Billing period (UTC)
	Date string `json:"date,omitempty"`
	// Total cost of bandwidth or pageview
	TotalCost float32 `json:"total_cost,omitempty"`
	// Page views processed by Platform Routing Tier
	ViewBase float32 `json:"view_base,omitempty"`
	// Page views processed by Varnish
	ViewVarnish float32 `json:"view_varnish,omitempty"`
	// Page views processed by ModSecurity
	ViewModsecurity float32 `json:"view_modsecurity,omitempty"`
	// Gigabytes processed through Australia
	DataAu float32 `json:"data_au,omitempty"`
	// Gigabytes processed through North America
	DataUs float32 `json:"data_us,omitempty"`
	// Gigabytes processed through Europe
	DataEu float32 `json:"data_eu,omitempty"`
	// Gigabytes processed by Varnish
	DataVarnish float32 `json:"data_varnish,omitempty"`
	// Gigabytes processed by ModSecurity
	DataModsecurity float32 `json:"data_modsecurity,omitempty"`
}
