/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type BillingSummary struct {
	// Billing enabled
	Enabled bool `json:"enabled,omitempty"`
	// Billing provisioning
	Provisioning bool `json:"provisioning,omitempty"`
	// Billing linked to user
	User string `json:"user,omitempty"`
	// Meter type for account
	MeterType string `json:"meter_type,omitempty"`
	// Account balance for period
	OutstandingBalance float32 `json:"outstanding_balance,omitempty"`
	// Next billing period starts
	PeriodNext string `json:"period_next,omitempty"`
	// Billing period started
	PeriodStarted string `json:"period_started,omitempty"`
	// Billing portal URL
	BillingPortal string `json:"billing_portal,omitempty"`
	// Account status
	State string `json:"state,omitempty"`
}
