/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Account struct {
	Id int32 `json:"id,omitempty"`
	Href string `json:"href,omitempty"`
	// user defined account name
	AccountName string `json:"account_name,omitempty"`
	// does authenticated account have access to account
	IsAdmin bool `json:"is_admin,omitempty"`
	// owner user id
	BillingUser int32 `json:"billing_user,omitempty"`
	// All users on this account must log in with 2FA
	Requires2fa bool `json:"requires_2fa,omitempty"`
	Owner *User `json:"owner,omitempty"`
}
