/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type AccountCreateRequest struct {
	Name string `json:"name"`
	Hostname string `json:"hostname"`
	Origin string `json:"origin,omitempty"`
	StackName string `json:"stackName,omitempty"`
}
