/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type CreateAccountResponse struct {
	Id int32 `json:"id,omitempty"`
	Href string `json:"href,omitempty"`
	AccountName string `json:"account_name,omitempty"`
	Applications []CreateAccountResponseApplications `json:"applications,omitempty"`
}
