/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type User struct {
	Id int32 `json:"id,omitempty"`
	Email string `json:"email,omitempty"`
	FirstName string `json:"first_name,omitempty"`
	LastName string `json:"last_name,omitempty"`
	CompanyName string `json:"company_name,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	Verified bool `json:"verified,omitempty"`
	Requires2fa bool `json:"requires2fa,omitempty"`
	Enforce2fa bool `json:"enforce2fa,omitempty"`
}
