/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Egress struct {
	RemoveRequestHeaders []HttpHeaderFieldName `json:"remove_request_headers,omitempty"`
	EnableSni bool `json:"enable_sni,omitempty"`
	UpstreamResponseTimeoutSeconds int32 `json:"upstream_response_timeout_seconds,omitempty"`
	VerifyCertificate bool `json:"verify_certificate,omitempty"`
	ProxyAcmeChallenge bool `json:"proxy_acme_challenge,omitempty"`
	Origins *EgressOrigins `json:"origins"`
}
