/*
 * Section API
 *
 * Get edgey with the Section API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sectionio

type Origin struct {
	// Hostname
	Hostname string `json:"hostname,omitempty"`
	// Hostname on a bare domain
	HostnameBare bool `json:"hostname_bare,omitempty"`
	// Hostname already exists on Section
	HostnameDuplicate bool `json:"hostname_duplicate,omitempty"`
	// Origin detected
	OriginDetected bool `json:"origin_detected,omitempty"`
	// Detected origin endpoint
	Origin string `json:"origin,omitempty"`
	// Detected origin fixed endpoint
	OriginFixed bool `json:"origin_fixed,omitempty"`
	// Detected origin ip
	OriginLookup string `json:"origin_lookup,omitempty"`
	// Origin multiple records
	OriginMultiple bool `json:"origin_multiple,omitempty"`
	// Origin hint found
	OriginHint string `json:"origin_hint,omitempty"`
	// Thirdparty detected
	ThirdpartyDetected bool `json:"thirdparty_detected,omitempty"`
	// Thirdparty name
	ThirdpartyName string `json:"thirdparty_name,omitempty"`
	// Detected application runnning on the origin
	OriginAppName string `json:"origin_app_name,omitempty"`
}
